### ISSUE TITLE
crest with gfnff for intermolecular complexes has problem with charges

### ISSUE THREAD

**Issue by robpollice** [grimme-lab/crest#5]
**Describe the bug**
Crest crashes when GFN-FF is used for intermolecular complexes together with specification of charge and/or multiplicity. I am using the pre-compiled version 2.10.1 together with the pre-compiled version 6.3.0 of xtb. Here are the files: [xtb.zip](https://github.com/grimme-lab/crest/files/4718852/xtb.zip)

**To Reproduce**
Steps to reproduce the behaviour:

1. XYZ with more than one molecule (see `mol.xyz` in the example).
2. Run `crest mol.xyz -chrg 0 -uhf 0 -gfnff -nci -mquick -opt loose` and the job crashes.
3. The outputs `crest.out` and `xtb.out` are provided in the ZIP file.
4. Run `crest mol.xyz -gfnff -nci -mquick -opt loose` and everything runs fine (after purging the folder of files from the previous run).

**Comment by robpollice** [comment]
[xtb.zip](https://github.com/grimme-lab/crest/files/4718847/xtb.zip)

**Comment by pprcht** [comment]
It seems to be that GFN-FF calculations fail in `xtb` if there is a `.CHRG` file with a specified molecular charge of `0` because it will produce a EEQ charge constrain error. This should be fixed with the upcoming `xtb 6.3.1` version.

For now please just refrain from using `-chrg 0` as a command line argument. The molecular charge of `0` is the default assumption and does not need specification.
