### ISSUE TITLE
Interest in a man page?

### ISSUE THREAD

**Issue by musicinmybrain** [grimme-lab/crest#56]
Would the authors be interested in maintaining a man page (`crest.1`), if I wrote the initial one based on the `crest --help` output and submitted a PR?

-----

If so, do you have a preference for where it should be located in the source tree? It could perhaps go at the root of the repository, in a new `doc` directory, or in `assets`, depending on your philosophy.

**Comment by awvwgk** [comment]
Thanks for the suggestion. We are maintaining a few man pages already for other projects and so far I found them to be a nice addition.

To make this effort maintainable I would ask you to not write the man page directly in roff, but use a markup language and a conversion tool. Some suggestions:
- [pandoc](https://pandoc.org/)
- [asciidoctor](https://asciidoctor.org/)
- [txt2man](https://github.com/mvertes/txt2man)

I'm personally prefer asciidoctor because the preview of the man page in GitHub looks pretty decent.

**Comment by musicinmybrain** [comment]
I wrote a man page using asciidoc, and set it up to be automatically built and installed when using meson. (https://github.com/grimme-lab/crest/pull/60)

I didn’t add it to the CMake scripts—mostly because I don’t like writing CMake very much, and somebody who writes CMake frequently could probably do it much faster using the meson support as a model.
