### ISSUE TITLE
Parallel version on specific .xyz file fails (please close)

### ISSUE THREAD

**Issue by totzstangolo** [grimme-lab/crest#6]
Hi,

just wanted to let you know that `crest -T 2 h2s2.xyz` fails (2 can be also n >= 2 threads) where h2s2.xyz is

```
4

S          0.94338       -0.04130        0.02811
S          2.98706        0.12675        0.03472
H          0.61504        1.25881        0.07922
H          3.31540       -1.17336       -0.01639
```

The serial version succeeds to generate conformers.

Thanks for the program and bye!

**Comment by pprcht** [comment]
That might be because the input has to be the first input argument, so in your case `crest h2s2.xyz -T 2`

Also I'm not sure what you mean by serial version, if the `-T` argument is not given the program will still try to parallelize depending on what is written in the `OMP_NUM_THREAD` system variable.

**Comment by totzstangolo** [comment]
> That might be because the input has to be the first input argument, so in your case `crest h2s2.xyz -T 2`
> 
> Also I'm not sure what you mean by serial version, if the `-T` argument is not given the program will still try to parallelize depending on what is written in the `OMP_NUM_THREAD` system variable.

Yes, I think I didn't set the environmental variables accordingly. Thank you
