### ISSUE TITLE
GFN-FF error (Initial geometry optimization failed)

### ISSUE THREAD

**Issue by ucb-mgcf** [grimme-lab/crest#61]
Hi,

I'm getting the above error when trying to run a crest simulation on a complex of 16 THF molecules (geometry attached).  The accompanying xtb.out file (also attached) shows that the GFN-FF topology setup failed (e.g. the qest values are ******).  My initial thought was to try including the charges file from a single-point GFN2 calculation, but the result is the same.

What's interesting is that a geometry optimization directly using xtb works.  I then tried adding --notopo to the crest input, and this works.  I just wanted to check if this is the expected behavior, and whether this approach for handling this error is ok (e.g. will using notopo cause other problems in the results?).

thanks

[thf16xyz.txt](https://github.com/grimme-lab/crest/files/6619583/thf16xyz.txt)
[xtb.out.txt](https://github.com/grimme-lab/crest/files/6619585/xtb.out.txt)

**Comment by pprcht** [comment]
Hi, 
I can't reproduce the setup fail on my machine with the THF input file, seems a bit strange. There shouldn't be an issue with the topology for this rather simple system. 
The `--notopo` option won't cause problems here. However, you should be careful with non-covalent systems or molecular clusters in general because the metadynamics potential will "push" the molecules apart. To prevent that, maybe also use the `--nci` option to generate a wall potential around the system.

**Comment by ucb-mgcf** [comment]
Hi,

Thanks for the reply.  Sorry for my delayed response, but I wanted to try installing xtb 6.4.1 and see if that had any impact on this situation, and I didn't get around to doing that until now.  I'm happy to report that this crest calculation, with the original keywords (i.e. without notopo), now proceeds beyond the initial geometry optimization and on to the metadynamics iterations.  I was using xtb 6.4.0 before, so this appears to have been the issue, in case you want to add a line for this in e.g. the release notes.

best regards
