### ISSUE TITLE
Constraints not respected for initial geometry optimization

### ISSUE THREAD

**Issue by kjelljorner** [grimme-lab/crest#66]
It seems that the constraints given by the command line options such as `--cinp`, `--cbonds` etc are not respected for the initial geometry optimization with xtb. This is problematic in cases where one wants to enforce a certain topology by constraints. That could be for example when there are known issues with the GFN methods as compared to higher level methods, or if you just want to explore the conformer space given that a certain conformer is stable. It might well be that, e.g., the initial conformer dissociates while lower energy conformers in the ensemble would be stable.

Is there any rationale for the current behaviour? For me it makes sense that the constraints should be enforced throughout all the calculations.

**Comment by pprcht** [comment]
That is surprising. The constraints should be recognized in the initial optimization for exactly the reasons you mentioned.
In the code the constraints are certainly passed to the `xtb` input.
Do you have an example where this happens? Maybe the force constant for the contraining potential is too low?

**Comment by kjelljorner** [comment]
I can't really see that they would be passed on in any apparent way. Here is the input xyz together with the crest and xtb output.
[crest.zip](https://github.com/grimme-lab/crest/files/6785855/crest.zip)

**Comment by kjelljorner** [comment]
By doing some experiments together with a colleague, it seems that explicit distance and atom constraints are being brought forward to the initial xtb optimization, while `--cbonds` or a xcontrol file with:
```
$constrain
  all bonds = True
```
does not work.

**Comment by pprcht** [comment]
Sorry, but I cannot confirm this.
With the `all bonds=True` there is no printout in the `xtb` output, so it is hard to check, but individual bond constraints generated with `--cbonds` will be printed out. 

However, both options are definitely passed form `crest` to `xtb`. For the initial optimization `crest` will write a temporary coord file called `tmpcoord` to use as an `xtb` input in which all constraints are appended after the actual coordinates. `xtb` will read those. In all tests I did the constraints were there and for `--cbonds` the bond constraints appeard also in the `xtb` output.

If still a topology mismatch is generated as in the `crest` output you provided, then there could be a geometry change due to changes in the bond angles, rather than in the bond lengths. Bond and dihedral angles are unaffected by the bond constraint and might change sigificantly during the optimization.

**Comment by kjelljorner** [comment]
That's very strange. Here you can see the full output from a CREST run on my end with `crest p_complex_ff.xyz --gfnff --cbonds 0.05 --keepdir -T 8 --verbose`. The contents of the tmpcoord file does not have any section for the constraints. 

[crest_github_issue.zip](https://github.com/grimme-lab/crest/files/6808792/crest_github_issue.zip)

**Comment by pprcht** [comment]
Alright, it seems to have something to do with the `--gfnff` flag. With the default GFN2 the `--cbonds` constraint is written to `tmpcoord` but with `--gfnff` I can reproduce your issue.
I'll have to look into that.

**Comment by pprcht** [comment]
With #67 the `--cbonds` option seems to work now in combination with `--gfnff` also for the initital geometry optimization. 

Concerning the `all bonds=True` contraining, this is written to `tmpcoord`, but still produces a topology mismatch. I'm unsure as of why.

**Comment by kjelljorner** [comment]
Thanks. I tested it on my end and both `--cbonds` and `--cmetal` works now. I think for `all bonds = True` it is just a matter of the magnitude of the force constant. Standard setting gives me topology change, while setting it higher gives the "expected" topology. Issue can be closed as far as I am concerned.
