### ISSUE TITLE
Reoptimization of CREST ensemble: wrong energies!?

### ISSUE THREAD

**Issue by cneiss** [grimme-lab/crest#82]
Hi,

I performed a CRE search on the gfn2//gfnff level and want to re-optimize the final CRE on the GFN2 level.
To do so, I started CREST with:
crest --forall conformers.xyz -prop reopt -alpb benzaldehyde -ewin 10 
(conformers.xyz is identical to the crest_conformers.xyz file produced by the preceding CREST run; I use implicit solvation and an energy window of 10 kcal/mol)

**expected result:** 
in the end, crest_property.xyz should contain the optimized geometries and energies on the GFN2 level

**current result:**
crest_property.xyz contains the optimized geometries on the GFN2 level, but the GFN2 energies **before** geometry optimization (which are significantly different from the energies after optimization)

To me, this looks like a bug.
I am using CREST 2.11.1.

Best,
Christian

**Comment by pprcht** [comment]
Hi,
I didn't touch the `-prop reopt` command for a while, there might be this error as you describe it.
You could use `crest --mdopt conformers.xyz --gfn2 --alpb benzahdehyde`, this will do the optimization of the ensemble as well and I know the output file has the correct energies written.
Structures in the output file `crest_ensemble.xyz` will not be sorted/have a threshold applied, if you want that use `--screen` instead of `--mdopt`, or sort the ensemble with `--cregen`.

**Comment by cneiss** [comment]
Hi Philipp,

thank you very much for pointing out the possible workarounds; it did the job! :-)

Best,
Christian
