### ISSUE TITLE
Constrains are partially ignored for the conformational analysis

### ISSUE THREAD

**Issue by andarcom** [grimme-lab/crest#86]
Hello, i am trying to do a conformational analysis for some aromatic systems. For the project two aromatic systems are supposed to stay in one plane, which i tried to implement with some constrains in a `.constrains` file.

The command i used:
`crest File.xyz -chrg 0 -gfn2 -ewin 6 -rthr 0.125 -ethr 0.05 -bthr 0.01 -T 8`

The constrain file:
 ```
$constrain
   > cat .xcontrol
   angle: 15,16,42, auto
   angle: 4,45,27, auto
   distance: 16,42, auto
   distance: 4,45, auto
   force constant= 0.5
```

For a lot of my structures that worked well, however for some, crest keeps replying: A new lower conformer was found!, which usually ignores the constrains I set. I already tried to increase the force constant stepwise to 10.0 however I either got the same result or starting from a force constant of 6.0 the Trial MTD did not converge.

Before the conformational analysis i always do a pre-optimization with xtb and the same constrains (in an `.inp` file).

`xtb File.xyz --input Nam5Sics_const.inp --gfn2 --opt --charge 0`

i have tested to use the `-nci` command, which also didnt solve the problem.

Did I misunderstand something about the constrains? Does anyone have further suggestions?

**Comment by pprcht** [comment]
Constraining angles can for some reason be annoying in the calculations, I'm not entirely sure why.
You could try to specify a reference constraint structure by adding `reference=<copy-of-your-input-coord>` to provide xtb/crest with an reference geometrical data. Here, you could specify atoms of the aromatic system to be fixed as in the reference.
Furthermore, maybe remove the atoms of the aromatic system from the metadynamics potential. Otherwise the metadynamics and the constraint try to counteract each other.
As of how to apply those correctly: The example section of the online documentation was cleaned up recently, both of the above constraining options are used e.g. for the [tyrosine on graphene example](https://xtb-docs.readthedocs.io/en/latest/crestxmpl.html#conformational-search-of-tyrosine-on-a-graphene-surface).
Also, remove the `> cat .xcontrol` from your file, thats entirely unrelated to the constraints.

**Comment by andarcom** [comment]
Jea that worked, thanks a lot.
